## iwls function directly derived from 
https://github.com/pysal/spglm/blob/master/spglm/iwls.py

In [5]:
import numpy as np
from scipy import linalg
import numpy.linalg as la
from scipy import sparse as sp
from scipy.sparse import linalg as spla
from spreg.utils import spdot, spmultiply
from scipy import special
import libpysal as ps

In [6]:
FLOAT_EPS = np.finfo(float).eps

### Fitting the MGWR model for the updated/adjusted dependent variables

#### This should remain the same as the GWR calculation given the partial smooth definition for process j (in this case the only 1) given in:
Yu, H., Fotheringham, S., Li, Z., Oshan, T., Kang, W., & Wolf, L. J. (2018). Inference in multiscale geographically weighted regression. doi:10.31219/osf.io/4dksb

\begin{align}
\hat{\beta} & _{ij}= e_j (X^T W_iX)^{-1} X^TW_i y \\
\end{align}

In [3]:
def compute_betas_mgwr(y,x,wi):
    xT = (x*wi).T
    xtx = np.dot(xT,x)
    xtx_inv_xt = linalg.solve(xtx, xT)
    betas = np.dot(xtx_inv_xt, y)
    return betas, xtx_inv_xt

In [ ]:
def compute_betas_mgwr(y,x,wi):
    xT = (x*wi).T
    xtx = np.dot(xT,x)
    xtx_inv_xt = linalg.solve(xtx, xT)
    betas = np.dot(xtx_inv_xt, y)
    return betas, xtx_inv_xt

#### I am confused if this is correct and remains the same as in GWPR and how to go about handling it for more than one dependent variables

### Only keeping the calculations for the log link function for now

In [39]:
def deriv (mu):
    p = np.clip(mu, FLOAT_EPS, np.inf)
    deriv_p = 1.0/p
    return deriv_p

def starting_mu(y):
    return (y+y.mean())/2
    
def weights(mu):
    p = np.clip(mu, FLOAT_EPS, np.inf)
    deriv_p = 1.0/p
    variance = np.ones(mu.shape,np.float64)
    return 1.0/(deriv_p**2 * variance)
    
def predict(mu):
    x = np.clip(mu, FLOAT_EPS, np.inf)
    return np.log(x)

def fitted(lin_pred):
    fits = np.exp(lin_pred)
    return fits

### Calling the weights function from below to calculate weights at each i

In [ ]:
wi = Kernel.ker(i=5,data=coords,bw=50,function='exponential')

### The function to do the Fischer scoring algorithm

In [143]:
def iwls(y, x, offset,
         ini_betas=None, tol=1.0e-06, max_iter=200, wi=None):
    
    n = x.shape[0]
    n_iter= 0
    diff = 1.0e+06
    
    if ini_betas is None:
        betas = np.zeros((x.shape[1],1), np.float)
    else:
        betas = ini_betas
        
    y_off = y/offset
    y_off = starting_mu(y_off)
    v = predict(y_off)
    mu = starting_mu(y)
        
    while diff > tol and n_iter < max_iter:
        n_iter +=1
        w = weights(mu)
        z = v + deriv(mu) * (y-mu)
        w = np.sqrt(w)
        
        if not isinstance(x, np.ndarray):
            w = sp.csr_matrix(w)
            z = sp.csr_matrix(z)
            
        wx = spmultiply(x,w,array_out=False)
        wz = spmultiply(z,w,array_out=False)
        
        n_betas, xtx_inv_xt = compute_betas_mgwr(wz, wx, wi)
        print(n_betas)
        v = spdot(x, n_betas)
        mu = fitted(v)
        mu = mu * offset
        
        diff = min(abs(n_betas - betas))
        #print(diff)
        betas = n_betas
        
    return betas, mu, v, w, z, xtx_inv_xt, n_iter      

### Trying with data

In [326]:
data_p = ps.io.open(ps.examples.get_path('Tokyomortality.csv'))
coords = list(zip(data_p.by_col('X_CENTROID'),data_p.by_col('Y_CENTROID')))
off = np.array(data_p.by_col('eb2564')).reshape((-1,1))
y = np.array(data_p.by_col('db2564')).reshape((-1,1)) 
occ = np.array(data_p.by_col('OCC_TEC')).reshape((-1,1))
own = np.array(data_p.by_col('OWNH')).reshape((-1,1))
pop = np.array(data_p.by_col('POP65')).reshape((-1,1))
unemp = np.array(data_p.by_col('UNEMP')).reshape((-1,1))
X = np.hstack([occ,own,pop,unemp])
x = occ

In [327]:
X_std = (X-X.mean(axis=0))/X.std(axis=0)
x_std = (x-x.mean(axis=0))/x.std(axis=0)
y_std = (y-y.mean(axis=0))/y.std(axis=0)
off_std = (off-off.mean(axis=0))/off.std(axis=0)

In [10]:
#rslt=iwls(y=y_std,x=x_std,offset=off_std,wi=wit,tol=1.0e-06, max_iter=200)

In [257]:
#do the result loop for each i 
#map the parameters back after

### Initialize using GWPR in MGWR

In [ ]:
initial_betas = GWR()

### Initialize using GWPR in MGWR for multiple variables

In [ ]:
betas=

#### Manually constructed weights for testing

In [ ]:
wi = np.diagonal(w)
wit=wi.reshape(-1,1)

In [142]:
rslt[0]

array([[-0.12618811]])

In [127]:
n_iter= 0
diff = 1.0e6
max_iter = 200
tol = 1.0e-06

In [128]:
while diff > tol and n_iter < max_iter:
        n_iter +=1
        print("+1")

+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1
+1


In [123]:
tol

NameError: name 'tol' is not defined

In [113]:
wit=wi.reshape(-1,1)

In [150]:
newwx=(wit*x_std).T

In [149]:
xstd_t=x_std.T

In [151]:
xtxx=np.dot(newwx,x_std)

In [152]:
xtxx.shape

(1, 1)

In [154]:
ls=linalg.solve(xtxx,newwx)

In [157]:
ls.shape

(1, 262)

In [158]:
y_std.shape

(262, 1)

In [155]:
np.dot(ls, y_std)

array([[0.33250184]])

In [103]:
(x_std*wi.T).shape

(262, 262)

In [37]:
mu=starting_mu(y_std)

In [88]:
we = weights(mu)

In [89]:
we

array([[8.78176024e-04],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [1.33784866e-03],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [4.93038066e-32],
       [2.70652703e-01],
       [6.12025921e-03],


In [38]:
deriv(mu)

In [ ]:
wi = 

In [15]:
xcc = np.array([1,2,4,6,8,7])
xcc_o=1/xcc

In [19]:
xcc+xcc*xcc

array([ 2,  6, 20, 42, 72, 56])

In [200]:
coords_i=coords[5]

### Limited functionality Kernel function for constructing weights for each point

In [189]:
def _kernel_funcs(zs,function):
    # functions follow Anselin and Rey (2010) table 5.4
    if function == 'triangular':
        return 1 - zs
    elif function == 'uniform':
        return np.ones(zi.shape) * 0.5
    elif function == 'quadratic':
        return (3. / 4) * (1 - zs**2)
    elif function == 'quartic':
        return (15. / 16) * (1 - zs**2)**2
    elif function == 'gaussian':
        return np.exp(-0.5 * (zs)**2)
    elif function == 'bisquare':
        return (1 - (zs)**2)**2
    elif function == 'exponential':
        return np.exp(-zs)
    else:
        print('Unsupported kernel function', function)

In [200]:
import numpy as np
#adaptive specifications should be parameterized with nn-1 to match original gwr
#implementation. That is, pysal counts self neighbors with knn automatically.

#Soft dependency of numba's njit
try:
    from numba import njit
except ImportError:

    def njit(func):
        return func


@njit
def local_cdist(coords_i, coords, spherical):
    """
    Compute Haversine (spherical=True) or Euclidean (spherical=False) distance for a local kernel.
    """
    if spherical:
        dLat = np.radians(coords[:, 1] - coords_i[1])
        dLon = np.radians(coords[:, 0] - coords_i[0])
        lat1 = np.radians(coords[:, 1])
        lat2 = np.radians(coords_i[1])
        a = np.sin(
            dLat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dLon / 2)**2
        c = 2 * np.arcsin(np.sqrt(a))
        R = 6371.0
        return R * c
    else:
        return np.sqrt(np.sum((coords_i - coords)**2, axis=1))


class Kernel(object):
    """
    GWR kernel function specifications.
    
    """

    def ker(i, data, bw, function, ids=None, points=None,fixed=True,
                 eps=1.0000001, spherical=False):
        
        dvec = np.sqrt(np.sum((np.array(coords[i]) - np.array(coords))**2, axis=1)).reshape(-1)

        bandwidth = float(bw)

        kernel = _kernel_funcs(dvec / bandwidth,function)

        if function == "bisquare":  #Truncate for bisquare
            kernel[(dvec >= bandwidth)] = 0
            
        return kernel

### Extra

In [44]:
import sys
sys.path.append("/Users/msachde1/Desktop/research_crime/crime_patterns_phoenix/mgwr-optim/mgwr_optim")

In [45]:
from mgwr.gwr import GWR
import numpy as np
from spglm.family import Gaussian, Binomial, Poisson
from mgwr.gwr import MGWR
from mgwr.sel_bw import Sel_BW
import multiprocessing as mp
pool = mp.Pool()

In [51]:
Sel_BW?

In [112]:
gwr_selector = Sel_BW(coords, y_std, x_std,family=Poisson(),offset=off)
bws=gwr_selector.search(pool=pool)

In [113]:
bws=gwr_selector.search(pool=pool)

In [114]:
bws

261.0

In [73]:
bw=gwr_selector.search()

In [91]:
Sel_BW?

In [79]:
model_gwr=GWR(coords, y_std, x_std, bw=bw, fixed=False, kernel='bisquare',family=Poisson(),offset=off)

In [80]:
results_gwr=model_gwr.fit()

In [90]:
Sel_BW.search?

In [87]:
results_gwr.tvalues[:,0]

array([-198.62752976, -195.34815347, -199.78793378, -197.56910643,
       -198.48232   , -200.06588007, -198.56727094, -199.40830771,
       -198.18295964, -199.21149657, -198.9389133 , -199.06447476,
       -199.30379944, -199.44712509, -199.62085504, -198.8529024 ,
       -198.80349307, -198.40902837, -198.19346457, -199.50771634,
       -199.11108225, -197.03960646, -197.84474149, -198.0577187 ,
       -194.75652617, -195.6860298 , -195.86003341, -197.58188816,
       -196.66662713, -199.55005145, -199.94136543, -200.20752568,
       -195.46084363, -195.91768455, -196.05024097, -196.78026905,
       -196.61073086, -196.07061779, -202.05650035, -198.13543566,
       -200.02271518, -200.70699516, -200.15662151, -197.59689713,
       -204.41218755, -203.22655628, -196.43248535, -199.93531949,
       -198.92812571, -198.02003618, -203.60284772, -196.37211381,
       -198.58216643, -199.62949794, -201.06561861, -200.16951488,
       -199.53225816, -201.62430267, -202.57806599, -204.10010

In [69]:
w=results_gwr.W

In [201]:
def build_wi (i, bw):
    wi = Kernel.ker(i=i, data=coords, bw=bw,function='exponential')
    return wi        

In [ ]:
fixed = True
spherical = False
function = 'bisquare'

In [ ]:
rslt = iwls(y, X, offset, ini_params, fit_params, max_iter, wi=wi)

In [ ]:
rslt_f = map()

## 6/3/2019 - within the MGWR loop

In [117]:
len(y_std)

262

In [116]:
class MGWR():
    """
    Multiscale GWR estimation and inference.
    Parameters
    ----------
    coords        : array-like
                    n*2, collection of n sets of (x,y) coordinates of
                    observatons; also used as calibration locations is
                    'points' is set to None
    y             : array
                    n*1, dependent variable
    X             : array
                    n*k, independent variable, exlcuding the constant
    selector      : sel_bw object
                    valid sel_bw object that has successfully called
                    the "search" method. This parameter passes on
                    information from GAM model estimation including optimal
                    bandwidths.
    family        : family object
                    underlying probability model; provides
                    distribution-specific calculations
    sigma2_v1     : boolean
                    specify form of corrected denominator of sigma squared to use for
                    model diagnostics; Acceptable options are:
                    'True':       n-tr(S) (defualt)
                    'False':     n-2(tr(S)+tr(S'S))
    kernel        : string
                    type of kernel function used to weight observations;
                    available options:
                    'gaussian'
                    'bisquare'
                    'exponential'
    fixed         : boolean
                    True for distance based kernel function and  False for
                    adaptive (nearest neighbor) kernel function (default)
    constant      : boolean
                    True to include intercept (default) in model and False to exclude
                    intercept.
    spherical     : boolean
                    True for shperical coordinates (long-lat),
                    False for projected coordinates (defalut).
    hat_matrix    : boolean
                    True for computing and storing covariate-specific
                    hat matrices R (n,n,k) and model hat matrix S (n,n).
                    False (default) for computing MGWR inference on the fly.
    Attributes
    ----------
    coords        : array-like
                    n*2, collection of n sets of (x,y) coordinates of
                    observatons; also used as calibration locations is
                    'points' is set to None
    y             : array
                    n*1, dependent variable
    X             : array
                    n*k, independent variable, exlcuding the constant
    selector      : sel_bw object
                    valid sel_bw object that has successfully called
                    the "search" method. This parameter passes on
                    information from GAM model estimation including optimal
                    bandwidths.
    bw            : array-like
                    collection of bandwidth values consisting of either a distance or N
                    nearest neighbors; user specified or obtained using
                    Sel_BW with fb=True. Order of values should the same as
                    the order of columns associated with X
    family        : family object
                    underlying probability model; provides
                    distribution-specific calculations
    sigma2_v1     : boolean
                    specify form of corrected denominator of sigma squared to use for
                    model diagnostics; Acceptable options are:
                    'True':       n-tr(S) (defualt)
                    'False':     n-2(tr(S)+tr(S'S))
    kernel        : string
                    type of kernel function used to weight observations;
                    available options:
                    'gaussian'
                    'bisquare'
                    'exponential'
    fixed         : boolean
                    True for distance based kernel function and  False for
                    adaptive (nearest neighbor) kernel function (default)
    constant      : boolean
                    True to include intercept (default) in model and False to exclude
                    intercept.
    spherical     : boolean
                    True for shperical coordinates (long-lat),
                    False for projected coordinates (defalut).
    n             : integer
                    number of observations
    k             : integer
                    number of independent variables
    mean_y        : float
                    mean of y
    std_y         : float
                    standard deviation of y
    fit_params    : dict
                    parameters passed into fit method to define estimation
                    routine
    W             : array-like
                    list of n*n arrays, spatial weights matrices for weighting all
                    observations from each calibration point: one for each
                    covariate (k)
    Examples
    --------
    #basic model calibration
    >>> import libpysal as ps
    >>> from mgwr.gwr import MGWR
    >>> from mgwr.sel_bw import Sel_BW
    >>> data = ps.io.open(ps.examples.get_path('GData_utm.csv'))
    >>> coords = list(zip(data.by_col('X'), data.by_col('Y')))
    >>> y = np.array(data.by_col('PctBach')).reshape((-1,1))
    >>> rural = np.array(data.by_col('PctRural')).reshape((-1,1))
    >>> fb = np.array(data.by_col('PctFB')).reshape((-1,1))
    >>> african_amer = np.array(data.by_col('PctBlack')).reshape((-1,1))
    >>> X = np.hstack([fb, african_amer, rural])
    >>> X = (X - X.mean(axis=0)) / X.std(axis=0)
    >>> y = (y - y.mean(axis=0)) / y.std(axis=0)
    >>> selector = Sel_BW(coords, y, X, multi=True)
    >>> selector.search(multi_bw_min=[2])
    [92.0, 101.0, 136.0, 158.0]
    >>> model = MGWR(coords, y, X, selector, fixed=False, kernel='bisquare', sigma2_v1=True)
    >>> results = model.fit()
    >>> print(results.params.shape)
    (159, 4)
    """

    def __init__(self, coords, y, X, selector, sigma2_v1=True,
                 kernel='bisquare', fixed=False, constant=True,
                 spherical=False, hat_matrix=False):
        """
        Initialize class
        """
        self.selector = selector
        self.bws = self.selector.bw[0]  #final set of bandwidth
        self.bws_history = selector.bw[1]  #bws history in backfitting
        #self.bw_init = self.selector.bw_init  #initialization bandiwdth
        self.family = Gaussian(
        )  # manually set since we only support Gassian MGWR for now
        GWR.__init__(self, coords, y, X, self.bw_init, family=self.family,
                     sigma2_v1=sigma2_v1, kernel=kernel, fixed=fixed,
                     constant=constant, spherical=spherical,
                     hat_matrix=hat_matrix)
        self.selector = selector
        self.sigma2_v1 = sigma2_v1
        self.points = None
        self.P = None
        self.offset = None
        self.exog_resid = None
        self.exog_scale = None
        self_fit_params = None

    def _chunk_compute_R(self, chunk_id=0,X,y):
        """
        Compute MGWR inference by chunks to reduce memory footprint.
        """
        #n = self.n
        #k = self.k
        #n_chunks = self.n_chunks
        n=262
        k=1
        n_chunks=1
        chunk_size = int(np.ceil(float(n / n_chunks)))
        #ENP_j = np.zeros(self.k)
        #CCT = np.zeros((self.n, self.k))
        ENP_j = np.zeros(k)
        CCT = np.zeros((n,k))

        chunk_index = np.arange(n)[chunk_id * chunk_size:(chunk_id + 1) *
                                   chunk_size]
        init_pR = np.zeros((n, len(chunk_index)))
        init_pR[chunk_index, :] = np.eye(len(chunk_index))
        pR = np.zeros((n, len(chunk_index),
                       k))  #partial R: n by chunk_size by k
        bw_init=selector.bw_init

        for i in range(n):
            wi = build_wi(i, bw_init).reshape(-1, 1)
            xT = (X * wi).T
            P = np.linalg.solve(xT.dot(X), xT).dot(init_pR).T
            pR[i, :, :] = P * self.X[i]

        err = init_pR - np.sum(pR, axis=2)  #n by chunk_size
        print(err) #checking the value
        
        for iter_i in range(self.bws_history.shape[0]):
            for j in range(k):
                pRj_old = pR[:, :, j] + err
                Xj = self.X[:, j]
                n_chunks_Aj = n_chunks
                chunk_size_Aj = int(np.ceil(float(n / n_chunks_Aj)))
                for chunk_Aj in range(n_chunks_Aj):
                    chunk_index_Aj = np.arange(n)[chunk_Aj * chunk_size_Aj:(
                        chunk_Aj + 1) * chunk_size_Aj]
                    pAj = np.empty((len(chunk_index_Aj), n))
                    for i in range(len(chunk_index_Aj)):
                        index = chunk_index_Aj[i]
                        wi = self._build_wi(index, self.bws_history[iter_i, j])
                        xw = Xj * wi
                        pAj[i, :] = Xj[index] / np.sum(xw * Xj) * xw
                    pR[chunk_index_Aj, :, j] = pAj.dot(pRj_old)
                err = pRj_old - pR[:, :, j]

        for j in range(k):
            CCT[:, j] += ((pR[:, :, j] / self.X[:, j].reshape(-1, 1))**2).sum(
                axis=1)
        for i in range(len(chunk_index)):
            ENP_j += pR[chunk_index[i], i, :]

        if self.hat_matrix:
            return ENP_j, CCT, pR
        return ENP_j, CCT

    def fit(self, n_chunks=1, pool=None):
        """
        Compute MGWR inference by chunk to reduce memory footprint.
        
        Parameters
        ----------
        n_chunks      : integer, optional
                        A number of chunks parameter to reduce memory usage. 
                        e.g. n_chunks=2 should reduce overall memory usage by 2.
        pool          : A multiprocessing Pool object to enable parallel fitting; default is None.
                        
        Returns
        -------
                      : MGWRResults
        """
        params = self.selector.params
        predy = np.sum(self.X * params, axis=1).reshape(-1, 1)

        try:
            from tqdm.autonotebook import tqdm  #progress bar
        except ImportError:

            def tqdm(x, total=0,
                     desc=''):  #otherwise, just passthrough the range
                return x

        if pool:
            self.n_chunks = pool._processes * n_chunks
            rslt = tqdm(
                pool.imap(self._chunk_compute_R, range(self.n_chunks)),
                total=self.n_chunks, desc='Inference')
        else:
            self.n_chunks = n_chunks
            rslt = map(self._chunk_compute_R,
                       tqdm(range(self.n_chunks), desc='Inference'))

        rslt_list = list(zip(*rslt))
        ENP_j = np.sum(np.array(rslt_list[0]), axis=0)
        CCT = np.sum(np.array(rslt_list[1]), axis=0)

        w = np.ones(self.n)
        if self.hat_matrix:
            R = np.hstack(rslt_list[2])
        else:
            R = None
        return MGWRResults(self, params, predy, CCT, ENP_j, w, R)

    def predict(self):
        '''
        Not implemented.
        '''
        raise NotImplementedError('N/A')

In [ ]:
GWR.__init__(self,coords, y, X, self.bw_init, family=self.family,
             sigma2_v1=sigma2_v1, kernel=kernel, fixed=fixed,
             constant=constant, spherical=spherical,
             hat_matrix=hat_matrix)

In [345]:
selector = selector_in
bws = selector.bw[0]  #final set of bandwidth
bws_history = selector.bw[1]  #bws history in backfitting
bw_init = selector.bw_init  #initialization bandiwdth
family = Gaussian()  # manually set since we only support Gassian MGWR for now
selector = selector
#sigma2_v1 = sigma2_v1
points = None
P = None
offset = None
exog_resid = None
exog_scale = None
self_fit_params = None

In [325]:
x_std.shape[1]

1

In [349]:
en,cct= _chunk_compute_R(x_std,y_std,coords,selector_in)

[[ 1.11022302e-016  4.66459341e-233  1.82574858e-093 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 1.67422270e-233  0.00000000e+000 -1.06980795e-262 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 5.57507982e-094 -9.10157404e-263  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 ...
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   9.47951000e-045 -4.36144234e-044]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  1.93419542e-044
   0.00000000e+000  3.79215097e-025]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ... -3.10693186e-042
   1.32395355e-023  0.00000000e+000]]


In [ ]:
self, coords, y, X, bw, family=Gaussian(), offset=None,
                 sigma2_v1=True, kernel='bisquare', fixed=False, constant=True,
                 spherical=False, hat_matrix=False

In [587]:
selector = selector_in
bws = selector.bw[0]  #final set of bandwidth
bws_history = selector.bw[1]  #bws history in backfitting
bw_init = selector.bw_init  #initialization bandiwdth
family = Gaussian()  # manually set since we only support Gassian MGWR for now
selector = selector
#sigma2_v1 = sigma2_v1
points = None
P = None
offset = None
exog_resid = None
exog_scale = None
self_fit_params = None

In [588]:
constant = True
sigma2_v1 = True
coords = coords
kernel = 'bisquare'
fixed = False
#if offset is None:
 #   self.offset = np.ones((self.n, 1))
#else:
 #   self.offset = offset * 1.0
fit_params = {}

points = None
exog_scale = None
exog_resid = None
P = None
spherical = False
hat_matrix = False

In [589]:
def _chunk_compute_R(X,y,coords,selector,n_chunks,chunk_id=0):
    """
    Compute MGWR inference by chunks to reduce memory footprint.
    """
    #n = self.n
    #k = self.k
    #n_chunks = self.n_chunks
    #selector = selector
    bws = selector.bw[0]  #final set of bandwidth
    bws_history = selector.bw[1]  #bws history in backfitting
    bw_init = selector.bw_init  #initialization bandiwdth
    family = Gaussian()  # manually set since we only support Gassian MGWR for now
    points = None
    P = None
    offset = None
    exog_resid = None
    exog_scale = None
    self_fit_params = None
    n=y.shape[0]
    k=X.shape[1]
    n_chunks=n_chunks
    chunk_size = int(np.ceil(float(n / n_chunks)))
    #ENP_j = np.zeros(self.k)
    #CCT = np.zeros((self.n, self.k))
    ENP_j = np.zeros(k)
    CCT = np.zeros((n,k))

    chunk_index = np.arange(n)[chunk_id * chunk_size:(chunk_id + 1) *
                               chunk_size]
    init_pR = np.zeros((n, len(chunk_index)))
    init_pR[chunk_index, :] = np.eye(len(chunk_index))
    pR = np.zeros((n, len(chunk_index),
                   k))  #partial R: n by chunk_size by k
    bw_init=selector.bw_init

    for i in range(n):
        wi = build_wi(i, bw_init).reshape(-1, 1)
        xT = (X * wi).T
        P = np.linalg.solve(xT.dot(X), xT).dot(init_pR).T
        pR[i, :, :] = P * X[i]

    err = init_pR - np.sum(pR, axis=2)  #n by chunk_size
    #print(err) #checking the value

    for iter_i in range(bws_history.shape[0]):
        for j in range(k):
            pRj_old = pR[:, :, j] + err
            Xj = X[:, j]
            n_chunks_Aj = n_chunks
            chunk_size_Aj = int(np.ceil(float(n / n_chunks_Aj)))
            for chunk_Aj in range(n_chunks_Aj):
                chunk_index_Aj = np.arange(n)[chunk_Aj * chunk_size_Aj:(
                    chunk_Aj + 1) * chunk_size_Aj]
                pAj = np.empty((len(chunk_index_Aj), n))
                for i in range(len(chunk_index_Aj)):
                    index = chunk_index_Aj[i]
                    wi = build_wi(index, bws_history[iter_i, j])
                    xw = Xj * wi
                    pAj[i, :] = Xj[index] / np.sum(xw * Xj) * xw
                pR[chunk_index_Aj, :, j] = pAj.dot(pRj_old)
            err = pRj_old - pR[:, :, j]

    for j in range(k):
        CCT[:, j] += ((pR[:, :, j] / X[:, j].reshape(-1, 1))**2).sum(
            axis=1)
    for i in range(len(chunk_index)):
        ENP_j += pR[chunk_index[i], i, :]

    if hat_matrix:
        return ENP_j, CCT, pR
    return ENP_j, CCT

In [ ]:
e,cc=_chunk_compute_R(x_std,y_std,coords,selector_in,n_chunks=1)

In [608]:
e

array([262.])

### ENP_j, CCT, pR, params

### Selector

In [599]:
selector_in = Sel_BW(coords, y_std, x_std, multi=True)
selector_in.search(multi_bw_min=[2])

array([ 23., 261.])

In [603]:
selector_gwrg = Sel_BW(coords, y_std, x_std).search()

In [604]:
selector_gwrg

85.0

In [601]:
selector_gwr = Sel_BW(coords, y_std, x_std,family=Poisson(),offset=off).search()

In [602]:
selector_gwr

261.0

In [ ]:
selector_inp = Sel_BW(coords, y_std, x_std, multi=True,family=Poisson(),offset=off)
selector_inp.search()

In [581]:
def fit(selector,X,y,coords,n_chunks=1, pool=None):
    constant = True
    sigma2_v1 = True
    coords = coords
    kernel = 'bisquare'
    fixed = False
    #if offset is None:
     #   self.offset = np.ones((self.n, 1))
    #else:
     #   self.offset = offset * 1.0
    fit_params = {}

    points = None
    exog_scale = None
    exog_resid = None
    P = None
    spherical = False
    hat_matrix = False
    
    n=y.shape[0]
    
    params = selector.params
    predy = np.sum(X * params, axis=1).reshape(-1, 1)
    
    if pool:
        n_chunks = pool._processes * n_chunks
        print("this")
        print(n_chunks)
        print(_chunk_compute_R(X,y,coords,selector,n_chunks))
        rslt = pool.imap(_chunk_compute_R(X,y,coords,selector,n_chunks), range(n_chunks))
    else:
        n_chunks = n_chunks
        print(n_chunks)
        print(_chunk_compute_R(X,y,coords,selector,n_chunks))
        r = map(_chunk_compute_R(X,y,coords,selector,n_chunks),
                   tqdm(range(n_chunks), desc='Inference'))
        
    rslt_list = list(zip(*rslt))
    ENP_j = np.sum(np.array(rslt_list[0]), axis=0)
    CCT = np.sum(np.array(rslt_list[1]), axis=0)

    w = np.ones(n)
    if hat_matrix:
        R = np.hstack(rslt_list[2])
    else:
        R = None
    return params, predy, CCT, ENP_j, w, R

In [554]:
n_chunks=12

In [511]:
selector_in.bw[0]

array([ 23., 261.])

In [553]:
fit(selector_in,x_std,y_std,coords,pool=pool)

this
12
(array([22.]), array([[3.20888813e+001],
       [1.15173882e+001],
       [9.79861500e+000],
       [8.44390203e-001],
       [8.44390203e-001],
       [3.64578378e+000],
       [5.81432345e-001],
       [1.31531956e+001],
       [1.39094861e-001],
       [8.44390203e-001],
       [1.70493508e+000],
       [6.20661337e+001],
       [4.70009862e+001],
       [5.02533300e-001],
       [3.98434573e-001],
       [6.80483234e-001],
       [5.02533300e-001],
       [6.53472826e-001],
       [3.72888353e+000],
       [8.84231729e-001],
       [8.44390203e-001],
       [3.23624706e-001],
       [6.16414886e-205],
       [0.00000000e+000],
       [4.26855501e-164],
       [1.44522447e-304],
       [9.94811062e-248],
       [1.32835595e-275],
       [0.00000000e+000],
       [4.16417688e-246],
       [4.83967094e-162],
       [1.01590590e-241],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000000e+000],
       [0.00000

TypeError: 'tuple' object is not callable

In [543]:
t_s=map(_chunk_compute_R(x_std,y_std,coords,selector_in),range(3))

In [545]:
list(zip(*t_s))

TypeError: 'tuple' object is not callable

In [534]:
fit(selector_in,x_std,y_std,coords)

1
(array([262.]), array([[3.20888813e+01],
       [1.15173882e+01],
       [9.79861500e+00],
       [8.44390203e-01],
       [8.44390203e-01],
       [3.64578378e+00],
       [5.81432345e-01],
       [1.31531956e+01],
       [1.39094861e-01],
       [8.44390203e-01],
       [1.70493508e+00],
       [6.20661337e+01],
       [4.70009862e+01],
       [5.02533300e-01],
       [3.98434573e-01],
       [6.80483234e-01],
       [5.02533300e-01],
       [6.53472826e-01],
       [3.72888353e+00],
       [8.84231729e-01],
       [8.44390203e-01],
       [3.23624706e-01],
       [5.81432345e-01],
       [5.20679845e-01],
       [5.81432345e-01],
       [5.39827346e-01],
       [3.42690616e-01],
       [4.24605371e-01],
       [5.39827346e-01],
       [1.58815466e+01],
       [1.15173882e+01],
       [9.79861500e+00],
       [1.70493508e+00],
       [3.86247339e-01],
       [5.02533300e-01],
       [5.02533300e-01],
       [3.10551673e+00],
       [6.80483234e-01],
       [3.20888813e+01],
       

TypeError: 'tuple' object is not callable

In [449]:
n=262

In [486]:
pool._processes?

In [493]:
reslt = map(_chunk_compute_R(x_std,y_std,coords,selector_in),
                       tqdm(range(n_chunks), desc='Inference'))

[[ 1.11022302e-016  4.66459341e-233  1.82574858e-093 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 1.67422270e-233  0.00000000e+000 -1.06980795e-262 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 5.57507982e-094 -9.10157404e-263  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 ...
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   9.47951000e-045 -4.36144234e-044]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  1.93419542e-044
   0.00000000e+000  3.79215097e-025]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ... -3.10693186e-042
   1.32395355e-023  0.00000000e+000]]


In [484]:
list(zip(*reslt))

[]

In [450]:
rslt = map(_chunk_compute_R(x_std,y_std,n_chunks,coords,selector_in), range(n))

[[ 1.11022302e-016  4.66459341e-233  1.82574858e-093 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 1.67422270e-233  0.00000000e+000 -1.06980795e-262 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 5.57507982e-094 -9.10157404e-263  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 ...
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   9.47951000e-045 -4.36144234e-044]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  1.93419542e-044
   0.00000000e+000  3.79215097e-025]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ... -3.10693186e-042
   1.32395355e-023  0.00000000e+000]]


In [453]:
rslt

In [443]:
n_chunks=1

In [444]:
n=y_std.shape[0]

params = selector_in.params
predy = np.sum(x_std * params, axis=1).reshape(-1, 1)

from tqdm.autonotebook import tqdm  #progress bar

n_chunks = pool._processes * n_chunks
rslt = tqdm(
    pool.imap(_chunk_compute_R(x_std,y_std,n_chunks,coords,selector_in), range(n_chunks)),
    total=n_chunks, desc='Inference')

rslt_list = list(zip(*rslt))
ENP_j = np.sum(np.array(rslt_list[0]), axis=0)
CCT = np.sum(np.array(rslt_list[1]), axis=0)

w = np.ones(self.n)
if hat_matrix:
    R = np.hstack(rslt_list[2])
else:
    R = None
#print(params, predy, CCT, ENP_j, w, R)

[[ 1.11022302e-016  4.66459341e-233  1.82574858e-093 ...  3.34925226e-094
   8.27636143e-101  7.05921463e-152]
 [ 1.67422270e-233  0.00000000e+000 -1.06980795e-262 ... -8.78104352e-198
  -9.15138470e-171 -2.51256429e-084]
 [ 5.57507982e-094 -9.10157404e-263  0.00000000e+000 ... -1.13256600e-065
  -4.77941251e-092 -1.42311623e-198]
 ...
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]]


TypeError: 'tuple' object is not callable

In [358]:
from tqdm.autonotebook import tqdm

In [362]:
n_chunks=1

In [398]:
n_chunks=3

In [413]:
rslt = map(_chunk_compute_R(x_std,y_std,coords,selector_in),
                   tqdm(range(n_chunks), desc='Inference'))

TypeError: _chunk_compute_R() missing 1 required positional argument: 'selector'

In [414]:
rslt = map(_chunk_compute_R(x_std,y_std,coords,selector_in),
                   tqdm(range(n_chunks), desc='Inference'))

TypeError: _chunk_compute_R() missing 1 required positional argument: 'selector'

In [371]:
list(zip(*rslt))

[]

In [416]:
r=fit(selector=selector_in,X=x_std,y=y_std,coords=coords)

[[ 1.11022302e-016  4.66459341e-233  1.82574858e-093 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 1.67422270e-233  0.00000000e+000 -1.06980795e-262 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 5.57507982e-094 -9.10157404e-263  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 ...
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   9.47951000e-045 -4.36144234e-044]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  1.93419542e-044
   0.00000000e+000  3.79215097e-025]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ... -3.10693186e-042
   1.32395355e-023  0.00000000e+000]]


IndexError: list index out of range

In [395]:
list(zip(*r))

[]

In [396]:
rslt_list = list(zip(*r))
ENP_j = np.sum(np.array(rslt_list[0]), axis=0)
CCT = np.sum(np.array(rslt_list[1]), axis=0)

w = np.ones(self.n)
if hat_matrix:
    R = np.hstack(rslt_list[2])
else:
    R = None
print(params, predy, CCT, ENP_j, w, R)

IndexError: list index out of range

In [383]:
n=y.shape[0]

params = selector_in.params
predy = np.sum(x_std * params, axis=1).reshape(-1, 1)

try:
    from tqdm.autonotebook import tqdm  #progress bar
except ImportError:

    def tqdm(x, total=0,
             desc=''):  #otherwise, just passthrough the range
        return x

if pool:
    n_chunks = pool._processes * n_chunks
    rslt = tqdm(
        pool.imap(_chunk_compute_R(x_std,y_std,coords,selector_in), range(n_chunks)),
        total=n_chunks, desc='Inference')
else:
    n_chunks = n_chunks
    rslt = map(_chunk_compute_R(x_std,y_std,coords,selector_in),
               tqdm(range(n_chunks), desc='Inference'))

[[ 1.11022302e-016  4.66459341e-233  1.82574858e-093 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 1.67422270e-233  0.00000000e+000 -1.06980795e-262 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 5.57507982e-094 -9.10157404e-263  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 ...
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   9.47951000e-045 -4.36144234e-044]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  1.93419542e-044
   0.00000000e+000  3.79215097e-025]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ... -3.10693186e-042
   1.32395355e-023  0.00000000e+000]]


In [388]:
%%time
rslt = map(_chunk_compute_R(x_std,y_std,coords,selector_in),
               tqdm(range(n_chunks), desc='Inference'))

[[ 1.11022302e-016  4.66459341e-233  1.82574858e-093 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 1.67422270e-233  0.00000000e+000 -1.06980795e-262 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 5.57507982e-094 -9.10157404e-263  0.00000000e+000 ...  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 ...
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  0.00000000e+000
   9.47951000e-045 -4.36144234e-044]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ...  1.93419542e-044
   0.00000000e+000  3.79215097e-025]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 ... -3.10693186e-042
   1.32395355e-023  0.00000000e+000]]


Wall time: 1.52 s


In [ ]:
rslt = map(_chunk_compute_R(x_std,y_std,coords,selector_in),
                   tqdm(range(n_chunks), desc='Inference'))

In [387]:
rslt_list = list(zip(*rslt))
ENP_j = np.sum(np.array(rslt_list[0]), axis=0)
CCT = np.sum(np.array(rslt_list[1]), axis=0)

w = np.ones(self.n)
if hat_matrix:
    R = np.hstack(rslt_list[2])
else:
    R = None
print(params, predy, CCT, ENP_j, w, R)

TypeError: 'tuple' object is not callable

In [341]:
pR.shape

(262, 86, 1)

In [208]:
wi = build_wi(0, 262).reshape(-1, 1)

In [262]:
n=262
bw_init=85.0

In [267]:
pR = np.zeros((262, len(chunk_index),1))

In [273]:
for i in range(n):
    wi = build_wi(i, bw_init).reshape(-1, 1)
    xT = (x_std * wi).T
    P = np.linalg.solve(xT.dot(x_std), xT).dot(init_pR).T
    pR[i, :, :] = P * x_std[i]

In [277]:
err = init_pR - np.sum(pR, axis=2)  #n by chunk_size

In [316]:
selector_in.params

array([[-4.45264152e-01,  2.00632789e-01],
       [-4.09741446e-01,  1.97245388e-01],
       [-5.11642161e-01,  1.98619991e-01],
       [-3.60414516e-01,  1.99022268e-01],
       [-3.72825304e-01,  1.96852653e-01],
       [-3.73268358e-01,  1.95586470e-01],
       [-3.22434590e-01,  1.95930622e-01],
       [-4.86601322e-01,  1.99289611e-01],
       [-4.20476610e-01,  1.99430308e-01],
       [-4.69013155e-01,  2.01092744e-01],
       [-4.57950892e-01,  2.01534855e-01],
       [-4.63565885e-01,  2.00297545e-01],
       [-4.72511476e-01,  1.98329751e-01],
       [-4.79224967e-01,  2.00499956e-01],
       [-4.85015144e-01,  1.99913284e-01],
       [-4.52802060e-01,  2.02360594e-01],
       [-4.51176406e-01,  2.02558606e-01],
       [-4.49452674e-01,  2.02114772e-01],
       [-4.31992722e-01,  2.00576390e-01],
       [-4.23129483e-01,  1.96931615e-01],
       [-3.94562225e-01,  1.96743259e-01],
       [-3.39640649e-01,  1.98273697e-01],
       [-3.58569744e-01,  1.98438599e-01],
       [-3.

In [298]:
pR[0, :,:].shape

(86, 1)

In [315]:
#x_std[:,0]

In [288]:
for iter_i in range(selector_in.bw[1].shape[0]):
    for j in range(k):
        pRj_old = pR[:, :, j] + err
        Xj = self.X[:, j]
        n_chunks_Aj = n_chunks
        chunk_size_Aj = int(np.ceil(float(n / n_chunks_Aj)))
        for chunk_Aj in range(n_chunks_Aj):
            chunk_index_Aj = np.arange(n)[chunk_Aj * chunk_size_Aj:(
                chunk_Aj + 1) * chunk_size_Aj]
            pAj = np.empty((len(chunk_index_Aj), n))
            for i in range(len(chunk_index_Aj)):
                index = chunk_index_Aj[i]
                wi = self._build_wi(index, self.bws_history[iter_i, j])
                xw = Xj * wi
                pAj[i, :] = Xj[index] / np.sum(xw * Xj) * xw
            pR[chunk_index_Aj, :, j] = pAj.dot(pRj_old)
        err = pRj_old - pR[:, :, j]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
for i in range(n):
    wi = build_wi(0, 262).reshape(-1, 1)
    xT = (self.X * wi).T
    P = np.linalg.solve(xT.dot(self.X), xT).dot(init_pR).T
    pR[i, :, :] = P * self.X[i]

In [ ]:
def __init__(self, coords, y, X, selector, sigma2_v1=True,
                 kernel='bisquare', fixed=False, constant=True,
                 spherical=False, hat_matrix=False):

In [226]:
selector_in.bw[1]

array([[ 23.,  94.],
       [ 23., 168.],
       [ 23., 253.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.]])

In [ ]:
self.selector = selector
self.bws = self.selector.bw[0]  #final set of bandwidth
self.bws_history = selector.bw[1]  #bws history in backfitting
        #self.bw_init = self.selector.bw_init  #initialization bandiwdth
self.family = Gaussian()  # manually set since we only support Gassian MGWR for now
GWR.__init__(self, coords, y, X, self.bw_init, family=self.family,
                     sigma2_v1=sigma2_v1, kernel=kernel, fixed=fixed,
                     constant=constant, spherical=spherical,
                     hat_matrix=hat_matrix)
self.selector = selector
self.sigma2_v1 = sigma2_v1
self.points = None
self.P = None
self.offset = None
self.exog_resid = None
self.exog_scale = None
self_fit_params = None

In [220]:
gwr_selector = Sel_BW(coords, y_std, x_std,family=Gaussian(),multi=True).search(pool=pool)
#bws=gwr_selector.search(pool=pool)

In [252]:
selector_in = Sel_BW(coords, y_std, x_std, multi=True)
selector_in.search(multi_bw_min=[2])

selector_inp = Sel_BW(coords, y_std, x_std, multi=True,family=Poisson(),offset=off)
#selector_inp.search()

array([ 23., 261.])

In [258]:
selector_in.bw_init

85.0

In [257]:
Sel_BW(coords, y_std, x_std,family=Poisson(),offset=off).search()

261.0

In [253]:
selector_in.bw[1]

array([[ 23.,  94.],
       [ 23., 168.],
       [ 23., 253.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.],
       [ 23., 261.]])

In [251]:
selector_inp = Sel_BW(coords, y_std, x_std, multi=True,family=Poisson(),offset=off)
#selector_inp.search()

C:\Users\msachde1\AppData\Local\Continuum\anaconda3\envs\gwrenv\lib\site-packages\spglm\family.py:111: RuntimeWarning: divide by zero encountered in true_divide
  return 1. / (self.link.deriv(mu)**2 * self.variance(mu))
C:\Users\msachde1\AppData\Local\Continuum\anaconda3\envs\gwrenv\lib\site-packages\spglm\iwls.py:34: RuntimeWarning: invalid value encountered in multiply
  xT = (x * wi).T
C:\Users\msachde1\AppData\Local\Continuum\anaconda3\envs\gwrenv\lib\site-packages\spglm\iwls.py:126: RuntimeWarning: invalid value encountered in greater
  while diff > tol and n_iter < max_iter:
C:\Users\msachde1\AppData\Local\Continuum\anaconda3\envs\gwrenv\lib\site-packages\spglm\family.py:111: RuntimeWarning: invalid value encountered in multiply
  return 1. / (self.link.deriv(mu)**2 * self.variance(mu))
C:\Users\msachde1\AppData\Local\Continuum\anaconda3\envs\gwrenv\lib\site-packages\spglm\iwls.py:129: RuntimeWarning: invalid value encountered in multiply
  z = v + (family.link.deriv(mu) * (y - m

Exception: one or more input arrays have missing/NaN values

In [241]:
selector_inp.

array([[ 5.92680698e-02],
       [-3.75800193e-01],
       [-4.91509838e-01],
       [-5.93334325e-01],
       [-5.14651767e-01],
       [-3.20259564e-01],
       [-5.14651767e-01],
       [-4.63739523e-01],
       [ 7.31532271e-02],
       [-6.90530426e-01],
       [-6.85902040e-01],
       [-5.23908538e-01],
       [-6.58131726e-01],
       [-7.36814284e-01],
       [-6.99787198e-01],
       [-7.36814284e-01],
       [-6.72016883e-01],
       [-6.90530426e-01],
       [-7.69212984e-01],
       [-6.21104640e-01],
       [-7.22929127e-01],
       [-6.30361411e-01],
       [-7.46071056e-01],
       [-5.97962711e-01],
       [-5.00766609e-01],
       [-7.36814284e-01],
       [-5.51678853e-01],
       [-6.30361411e-01],
       [-5.97962711e-01],
       [-5.88705939e-01],
       [-5.88705939e-01],
       [-6.90530426e-01],
       [-2.60090549e-01],
       [-6.85902040e-01],
       [-7.41442670e-01],
       [-7.50699441e-01],
       [-6.16476254e-01],
       [-6.81273655e-01],
       [ 1.0

In [242]:
selector_inp = Sel_BW(coords, y_std, x_std, family=Poisson(),offset=off)

In [249]:
selector_inp.search()

261.0